# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerball_checker', '0002_auto_20151206_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
