# Generated by Django 2.1.3 on 2018-11-15 14:08

from django.db import migrations


def create_states(apps, schema_editor):
    State = apps.get_model('cep', 'State')
    State.objects.bulk_create(
        [
            State(name='Acre', acronym='AC'),
            State(name='Alagoas', acronym='AL'),
            State(name='Amazonas', acronym='AM'),
            State(name='Amapá', acronym='AP'),
            State(name='Bahia', acronym='BA'),
            State(name='Ceara', acronym='CE'),
            State(name='Distrito Federal', acronym='DF'),
            State(name='Espirito Santo', acronym='ES'),
            State(name='Goiás', acronym='GO'),
            State(name='Maranhão', acronym='MA'),
            State(name='Minas Gerais', acronym='MG'),
            State(name='Mato Grosso do Sul', acronym='MS'),
            State(name='Mato Grosso', acronym='MT'),
            State(name='Pará', acronym='PA'),
            State(name='Paraíba', acronym='PB'),
            State(name='Pernambuco', acronym='PE'),
            State(name='Piauí', acronym='PI'),
            State(name='Paraná', acronym='PR'),
            State(name='Rio de Janeiro', acronym='RJ'),
            State(name='Rio Grande do Norte', acronym='RN'),
            State(name='Rondônia', acronym='RO'),
            State(name='Roraima', acronym='RR'),
            State(name='Rio Grande do Sul', acronym='RS'),
            State(name='Santa Catarina', acronym='SC'),
            State(name='Sergipe', acronym='SE'),
            State(name='São Paulo', acronym='SP'),
            State(name='Tocantins', acronym='TO')
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_states),
    ]
