# Generated by Django 2.1.3 on 2018-11-15 16:32

from django.db import migrations


def create_cities(apps, schema_editor):
    State = apps.get_model('cep', 'State')
    City = apps.get_model('cep', 'City')

    ba = State.objects.get(acronym='BA')
    sp = State.objects.get(acronym='SP')

    City.objects.bulk_create(
        [
            City(name='Jequié', state=ba),
            City(name='Salvador', state=ba),
            City(name='São Paulo', state=sp),
            City(name='Campinas', state=sp),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0003_city'),
    ]

    operations = [
        migrations.RunPython(create_cities),
    ]
