# Generated by Django 2.1.3 on 2018-11-15 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0004_load_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('cep', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^(\\d\\d\\.\\d\\d\\d-\\d\\d\\d|\\d\\d\\d\\d\\d-\\d\\d\\d|\\d\\d\\d\\d\\d\\d\\d\\d)$'), django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(10)])),
                ('public_place', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.City')),
            ],
        ),
    ]
