# Generated by Django 2.1.3 on 2018-11-15 22:17

from django.db import migrations


def create_ceps(apps, schema_editor):
    State = apps.get_model('cep', 'State')
    City = apps.get_model('cep', 'City')
    Cep = apps.get_model('cep', 'Cep')

    jequie = City.objects.get(name='Jequié', state=State.objects.get(acronym='BA'))
    campinas = City.objects.get(name='Campinas', state=State.objects.get(acronym='SP'))

    Cep.objects.bulk_create(
        [
            Cep(
                cep='45200621',
                public_place='Rua Doutor Mario Lins',
                neighborhood='Joaquim Romão',
                city=jequie,
            ),
            Cep(
                cep='45200560',
                public_place='Avenida Santa Luzia',
                neighborhood='Joaquim Romão',
                city=jequie,
            ),
            Cep(
                cep='13097252',
                public_place='Avenida 1',
                neighborhood='Alphaville Dom Pedro 3',
                city=campinas
            )
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0005_cep'),
    ]

    operations = [
        migrations.RunPython(create_ceps),
    ]
