# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('post_code', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=530)),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
