# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerball_checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='date',
            new_name='draw_date',
        ),
    ]
