# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='cep',
            new_name='zip_code',
        ),
    ]
