version: '3'

services:
  
  rabbit:
    hostname: my-rabbit
    image: rabbitmq:3-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    links:
      - my-rabbit
  
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: 
    volumes:
      - .:/app
    links:
      - my-rabbit
    depends_on:
      - rabbit